In [1]:
import numpy as np

In [2]:
A = np.random.randn(3, 3)
A_inv = np.linalg.inv(A)
A_inv_inv = np.linalg.inv(A_inv)

print(A)
print(A_inv)
print(A_inv_inv)

[[-0.61910794 -1.74397277 -1.11446029]
 [-0.08955587 -0.70645879  2.15175747]
 [ 1.34963844 -1.68072912 -0.6154958 ]]
[[-0.46529218 -0.09184439  0.52140536]
 [-0.32720131 -0.21651038 -0.16446086]
 [-0.12679119  0.38982978 -0.03229449]]
[[-0.61910794 -1.74397277 -1.11446029]
 [-0.08955587 -0.70645879  2.15175747]
 [ 1.34963844 -1.68072912 -0.6154958 ]]
