In [4]:
import numpy as np

In [5]:
A = np.random.randn(5, 5)
MUL = A.T @ A
PLS = A.T + A

In [6]:
evals, evecs = np.linalg.eig(MUL)
U, _, VT = np.linalg.svd(MUL)

print(np.round(evecs, 6))
print(np.round(U, 6))

[[ 0.756551  0.233571 -0.595144  0.088067  0.105463]
 [ 0.567252 -0.292214  0.471688 -0.506544 -0.337283]
 [-0.16823  -0.566007 -0.536837  0.038652 -0.601371]
 [-0.0894    0.717122  0.043498 -0.01408  -0.689676]
 [-0.263745  0.159463 -0.365004 -0.856718  0.194467]]
[[-0.756551  0.233571 -0.595144  0.105463 -0.088067]
 [-0.567252 -0.292214  0.471688 -0.337283  0.506544]
 [ 0.16823  -0.566007 -0.536837 -0.601371 -0.038652]
 [ 0.0894    0.717122  0.043498 -0.689676  0.01408 ]
 [ 0.263745  0.159463 -0.365004  0.194467  0.856718]]


In [7]:
evals, evecs = np.linalg.eig(PLS)
U, _, VT = np.linalg.svd(PLS)

print(np.round(evecs, 6))
print(np.round(U, 6))

[[ 0.221722 -0.639468 -0.214889  0.698692  0.087018]
 [-0.142671  0.202757  0.494368  0.285408  0.782737]
 [-0.43641   0.152893  0.452636  0.490347 -0.583825]
 [ 0.849405  0.378759  0.266111  0.18104  -0.177374]
 [-0.136166  0.61898  -0.65858   0.396429  0.086246]]
[[ 0.221722 -0.087018  0.698692  0.639468  0.214889]
 [-0.142671 -0.782737  0.285408 -0.202757 -0.494368]
 [-0.43641   0.583825  0.490347 -0.152893 -0.452636]
 [ 0.849405  0.177374  0.18104  -0.378759 -0.266111]
 [-0.136166 -0.086246  0.396429 -0.61898   0.65858 ]]
