In [1]:
import numpy as np

In [2]:
R3 = np.random.randn(5, 3) @ np.random.randn(3, 5)
U, s, Vt = np.linalg.svd(R3)
S_inv = np.zeros((5, 5))
s_inv = np.array(list(map(lambda x: 1 / x if x > 1e-6 else 0, s)))
np.fill_diagonal(S_inv, s_inv)
R3_inv = Vt.T @ S_inv @ U.T
R3_pinv = np.linalg.pinv(R3)

print(np.round(R3_inv, 6))
print(np.round(R3_pinv, 6))

[[ 0.1511   -0.176949  1.301186  0.402957 -0.878355]
 [-0.107809  0.011936 -0.431818 -0.222698  0.15213 ]
 [-0.064846 -0.465278  0.910066  0.16987  -0.866856]
 [ 0.0536    0.30937  -0.800285 -0.082491  0.830227]
 [-0.141    -0.219365  0.610721 -0.164356 -0.952436]]
[[ 0.1511   -0.176949  1.301186  0.402957 -0.878355]
 [-0.107809  0.011936 -0.431818 -0.222698  0.15213 ]
 [-0.064846 -0.465278  0.910066  0.16987  -0.866856]
 [ 0.0536    0.30937  -0.800285 -0.082491  0.830227]
 [-0.141    -0.219365  0.610721 -0.164356 -0.952436]]
