In [1]:
import numpy as np

In [2]:
TALL = np.random.randn(5, 3)
WIDE = np.random.randn(3, 5)

In [3]:
A = TALL
linv = np.linalg.inv(A.T @ A) @ A.T
pinv = np.linalg.pinv(A)

print(np.round(linv - pinv, 6))

[[-0. -0. -0. -0. -0.]
 [ 0.  0. -0. -0. -0.]
 [-0. -0. -0. -0.  0.]]


In [4]:
A = WIDE
rinv = A.T @ np.linalg.inv(A @ A.T)
pinv = np.linalg.pinv(A)

print(np.round(rinv - pinv, 6))

[[ 0. -0. -0.]
 [-0.  0. -0.]
 [-0.  0.  0.]
 [ 0. -0. -0.]
 [ 0.  0.  0.]]
