In [1]:
import numpy as np

In [2]:
A = np.array([[1, 0], [0, 1]])
evals, evecs = np.linalg.eig(A)
evecs_inv = np.linalg.pinv(evecs)

print(evecs @ evecs_inv)
print(np.round(evecs_inv @ A @ evecs - evals * evecs_inv @ evecs, 6))
print(np.round(A @ evecs @ evecs_inv - evals * evecs @ evecs_inv ,6))

[[1. 0.]
 [0. 1.]]
[[0. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 0.]]
