In [67]:
import numpy as np
import scipy

In [68]:
A = np.random.rand(4, 4)
P, L, U = scipy.linalg.lu(A)
A_inv = np.linalg.inv(U) @ np.linalg.inv(L) @ P.T

print(np.round(P, 6)) # This is transpose of row interchange matrix.
print(np.round(A @ A_inv, 6))

[[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]]
[[ 1.  0. -0. -0.]
 [-0.  1. -0. -0.]
 [ 0. -0.  1. -0.]
 [-0.  0.  0.  1.]]
