In [3]:
import numpy as np

In [4]:
R = np.array([1.0, 0.2, 0.9, 0.2, 1.0, 0.3, 0.9, 0.3, 1.0]).reshape(3, 3)
evals, evecs = np.linalg.eig(R)
X = np.random.randn(3, 10000)
Y = evecs @ np.diag(evals)**0.5 @ X
Y_bar = Y.T @ evecs @ np.linalg.inv(np.diag(evals))**0.5
R = np.corrcoef(Y_bar.T) # IDK why transpose.
print(R - np.eye(3))

[[-2.22044605e-16  1.46604346e-02 -8.00197592e-03]
 [ 1.46604346e-02  0.00000000e+00  8.18169554e-03]
 [-8.00197592e-03  8.18169554e-03 -2.22044605e-16]]
