In [54]:
import numpy as np
import scipy

In [55]:
A = np.random.randn(3, 3)
A = A.T @ A
evals, evecs = np.linalg.eig(A)
evecs /= np.linalg.norm(evecs, axis=0)

In [56]:
bases = np.zeros((3, 3))
for idx, eval in enumerate(evals):
    bases[idx] = scipy.linalg.null_space(A - eval * np.eye(3)).reshape(-1, 3)
bases /= np.linalg.norm(bases, axis=0)

In [57]:
print(bases)
print(evecs)

[[ 0.94711986 -0.32053169 -0.01494689]
 [ 0.31171216  0.9301161  -0.19421526]
 [-0.07615449 -0.179286   -0.98084506]]
[[ 0.94711986 -0.31171216  0.07615449]
 [-0.32053169 -0.9301161   0.179286  ]
 [-0.01494689  0.19421526  0.98084506]]
