In [1]:
import numpy as np

In [2]:
D = np.diag(np.random.randn(4)**2)
R = np.random.randn(4, 4)
q, r = np.linalg.qr(R)
M = q @ D @ q.T

In [3]:
print(M)

[[ 1.16301404 -0.20273673 -0.12771334 -0.60537625]
 [-0.20273673  0.4718073   1.10031464  0.75926566]
 [-0.12771334  1.10031464  3.23273933  1.93045453]
 [-0.60537625  0.75926566  1.93045453  1.53026397]]


In [4]:
evals, evecs = np.linalg.eig(M)
print(D)
print(evals)

[[4.95611949 0.         0.         0.        ]
 [0.         1.29161549 0.         0.        ]
 [0.         0.         0.06259361 0.        ]
 [0.         0.         0.         0.08749605]]
[4.95611949 1.29161549 0.08749605 0.06259361]
