In [76]:
import numpy as np

In [77]:
A = np.random.randint(-14, 15, 16).reshape(4, 4)
evals, evecs = np.linalg.eig(A)

In [78]:
print(A)
print(np.round(evecs @ np.diag(evals) @ np.linalg.inv(evecs), 6))

[[ -6  -1   7   3]
 [ -5 -12  -5  12]
 [ 14 -10   6   2]
 [  9  -7  -3  -5]]
[[ -6.+0.j  -1.-0.j   7.-0.j   3.+0.j]
 [ -5.+0.j -12.-0.j  -5.-0.j  12.-0.j]
 [ 14.+0.j -10.+0.j   6.-0.j   2.-0.j]
 [  9.+0.j  -7.+0.j  -3.-0.j  -5.-0.j]]


In [79]:
evecs2 = evecs * np.conj(evecs)
print(np.sqrt(np.sum(evecs2, axis=0)))

[1.+0.j 1.+0.j 1.+0.j 1.+0.j]


In [80]:
evecspi = np.pi * evecs
print(A)
print(np.round(evecspi @ np.diag(evals) @ np.linalg.inv(evecspi), 6))

[[ -6  -1   7   3]
 [ -5 -12  -5  12]
 [ 14 -10   6   2]
 [  9  -7  -3  -5]]
[[ -6.-0.j  -1.+0.j   7.+0.j   3.-0.j]
 [ -5.-0.j -12.-0.j  -5.+0.j  12.-0.j]
 [ 14.+0.j -10.-0.j   6.-0.j   2.+0.j]
 [  9.+0.j  -7.+0.j  -3.+0.j  -5.+0.j]]


In [81]:
A = A @ A.T
evalssym, evecssym = np.linalg.eig(A)
print(A)
print(np.round(evecssym @ np.diag(evalssym) @ evecssym.T, 6))

[[ 95  43 -26 -83]
 [ 43 338  44  -6]
 [-26  44 336 168]
 [-83  -6 168 164]]
[[ 95.  43. -26. -83.]
 [ 43. 338.  44.  -6.]
 [-26.  44. 336. 168.]
 [-83.  -6. 168. 164.]]
