In [1]:
# It seems that the exercise 1 has a typo...
import numpy as np

In [2]:
M = np.random.randn(5, 5)
Q = np.linalg.qr(M)[0]

print(np.round(Q.T @ Q, 6))
print(np.round(Q @ Q.T, 6))
print(np.round(np.linalg.inv(Q) @ Q, 6))
print(np.round(Q @ np.linalg.inv(Q), 6))

[[ 1.  0. -0.  0.  0.]
 [ 0.  1.  0.  0. -0.]
 [-0.  0.  1. -0. -0.]
 [ 0.  0. -0.  1.  0.]
 [ 0. -0. -0.  0.  1.]]
[[ 1.  0. -0.  0.  0.]
 [ 0.  1. -0. -0. -0.]
 [-0. -0.  1.  0. -0.]
 [ 0. -0.  0.  1. -0.]
 [ 0. -0. -0. -0.  1.]]
[[ 1. -0.  0.  0. -0.]
 [ 0.  1. -0.  0.  0.]
 [ 0. -0.  1.  0.  0.]
 [ 0.  0. -0.  1.  0.]
 [ 0. -0. -0.  0.  1.]]
[[ 1. -0. -0. -0.  0.]
 [ 0.  1. -0. -0.  0.]
 [-0.  0.  1.  0. -0.]
 [-0. -0.  0.  1.  0.]
 [-0.  0.  0.  0.  1.]]
