In [1]:
import numpy as np

In [2]:
M = np.random.randn(4, 4)

In [3]:
# Answer.
answer = np.linalg.qr(M)[0]

In [4]:
def qr(m):
    q = m.copy()
    q[:, 0] /= np.linalg.norm(q[:, 0])
    for i in range(1, m.shape[1]):
        q[:, i] = m[:, i]
        for j in range(i):
            q[:, i] -= np.dot(m[:, i].T, q[:, j]) * q[:, j]
        q[:, i] /= np.linalg.norm(q[:, i])
    return q

In [5]:
# My answer
my_answer = qr(M)

In [6]:
print(answer)
print(my_answer)
print(np.round(answer - my_answer, 6))
print(np.round(answer + my_answer, 6))

[[-0.27194507  0.71071948 -0.07373322 -0.6445829 ]
 [-0.19004745 -0.26424128 -0.93984678 -0.10366553]
 [-0.53868677  0.43393941 -0.09207945  0.71626429]
 [-0.77443167 -0.48657061  0.32058199 -0.24643824]]
[[ 0.27194507 -0.71071948 -0.07373322  0.6445829 ]
 [ 0.19004745  0.26424128 -0.93984678  0.10366553]
 [ 0.53868677 -0.43393941 -0.09207945 -0.71626429]
 [ 0.77443167  0.48657061  0.32058199  0.24643824]]
[[-0.54389   1.421439  0.       -1.289166]
 [-0.380095 -0.528483 -0.       -0.207331]
 [-1.077374  0.867879  0.        1.432529]
 [-1.548863 -0.973141  0.       -0.492876]]
[[ 0.        0.       -0.147466  0.      ]
 [ 0.       -0.       -1.879694  0.      ]
 [ 0.        0.       -0.184159  0.      ]
 [ 0.       -0.        0.641164 -0.      ]]
