In [1]:
import numpy as np

In [2]:
M = np.random.randn(6, 6)
U = np.linalg.qr(M)[0]
U_Q, U_R = np.linalg.qr(U)
print(np.allclose(U_R, np.eye(6, 6)))

True


In [3]:
S = np.diag(np.arange(10, 16, 1)/ np.linalg.norm(U, axis=0))
V = U @ S
V_Q, V_R = np.linalg.qr(V)
print(np.round(V_R, 6))
print(np.round(V_Q.T @ V_Q, 6))

[[10. -0.  0. -0.  0. -0.]
 [ 0. 11. -0.  0.  0.  0.]
 [ 0.  0. 12. -0.  0. -0.]
 [ 0.  0.  0. 13. -0.  0.]
 [ 0.  0.  0.  0. 14. -0.]
 [ 0.  0.  0.  0.  0. 15.]]
[[ 1. -0.  0. -0.  0. -0.]
 [-0.  1. -0.  0.  0.  0.]
 [ 0. -0.  1. -0.  0. -0.]
 [-0.  0. -0.  1. -0.  0.]
 [ 0.  0.  0. -0.  1. -0.]
 [-0.  0. -0.  0. -0.  1.]]


In [4]:
W = U.copy()
W[1, 4] = 0
W_Q, W_R = np.linalg.qr(W)
print(np.round(W_R, 6))

[[ 1.       -0.        0.       -0.       -0.025089 -0.      ]
 [ 0.        1.       -0.        0.        0.30729   0.      ]
 [ 0.        0.        1.        0.        0.090679 -0.      ]
 [ 0.        0.        0.        1.        0.107676 -0.      ]
 [ 0.        0.        0.        0.        0.665726 -0.545241]
 [ 0.        0.        0.        0.        0.        0.83828 ]]
