In [1]:
import numpy as np

In [2]:
A = np.random.randn(10, 4)
Q, R = np.linalg.qr(A, "complete")

In [3]:
print(np.round(R, 6))

[[-3.595736  1.047776 -1.049375  1.952442]
 [ 0.       -2.372745 -1.027598  0.195622]
 [ 0.        0.       -3.24217  -0.21761 ]
 [ 0.        0.        0.        2.405087]
 [ 0.        0.        0.        0.      ]
 [ 0.        0.        0.        0.      ]
 [ 0.        0.        0.        0.      ]
 [ 0.        0.        0.        0.      ]
 [ 0.        0.        0.        0.      ]
 [ 0.        0.        0.        0.      ]]


In [4]:
SQ = R[:4, :]
SQ_inv = np.linalg.inv(SQ)
HI = R
HI_inv = np.linalg.pinv(HI)

print(np.round(SQ_inv, 6))
print(np.round(HI_inv, 6))

[[-0.278107 -0.122809  0.128937  0.247421]
 [ 0.       -0.421453  0.133578  0.046366]
 [ 0.        0.       -0.308435 -0.027907]
 [ 0.        0.        0.        0.415785]]
[[-0.278107 -0.122809  0.128937  0.247421  0.        0.        0.
   0.        0.        0.      ]
 [-0.       -0.421453  0.133578  0.046366  0.        0.        0.
   0.        0.        0.      ]
 [-0.        0.       -0.308435 -0.027907  0.        0.        0.
   0.        0.        0.      ]
 [ 0.       -0.       -0.        0.415785  0.        0.        0.
   0.        0.        0.      ]]
